-- EstadoBahia
INSERT INTO ESTADO_BAHIA (ID_ESTADO, CODIGO, NOMBRE) VALUES (1, 'DISPONIBLE',    'Disponible');
INSERT INTO ESTADO_BAHIA (ID_ESTADO, CODIGO, NOMBRE) VALUES (2, 'OCUPADA',       'Ocupada');
INSERT INTO ESTADO_BAHIA (ID_ESTADO, CODIGO, NOMBRE) VALUES (3, 'MANTENIMIENTO', 'Mantenimiento');
INSERT INTO ESTADO_BAHIA (ID_ESTADO, CODIGO, NOMBRE) VALUES (4, 'INACTIVA',      'Inactiva');

-- Rol
INSERT INTO ROL (ID_ROL, NOMBRE, DESCRIPCION) VALUES (1, 'ADMIN',    'Acceso total al sistema');
INSERT INTO ROL (ID_ROL, NOMBRE, DESCRIPCION) VALUES (2, 'OPERADOR', 'Gestiona bahías y reservas');
INSERT INTO ROL (ID_ROL, NOMBRE, DESCRIPCION) VALUES (3, 'CONSULTA', 'Solo puede ver reportes y estados');

-- Permiso
INSERT INTO PERMISO (ID_PERMISO, CODIGO, DESCRIPCION) VALUES (1, 'BAHIA_VER',        'Ver listado de bahías');
INSERT INTO PERMISO (ID_PERMISO, CODIGO, DESCRIPCION) VALUES (2, 'BAHIA_EDITAR',     'Crear y modificar bahías');
INSERT INTO PERMISO (ID_PERMISO, CODIGO, DESCRIPCION) VALUES (3, 'RESERVA_CREAR',    'Crear nuevas reservas');
INSERT INTO PERMISO (ID_PERMISO, CODIGO, DESCRIPCION) VALUES (4, 'RESERVA_CANCELAR', 'Cancelar reservas');
INSERT INTO PERMISO (ID_PERMISO, CODIGO, DESCRIPCION) VALUES (5, 'REPORTE_VER',      'Visualizar reportes');

-- Rol_Permiso
-- Asignar todos los permisos al rol ADMIN
INSERT INTO ROL_PERMISO (ID_ROL, ID_PERMISO) SELECT 1, ID_PERMISO FROM PERMISO;

-- Crear usuario admin
INSERT INTO USUARIO (ID_USUARIO, USERNAME, NOMBRE, EMAIL, HASH_PASS, ACTIVO)
VALUES (1, 'admin', 'Administrador', 'admin@demo.local', 'admin123', 'S');

-- Relacionar con rol ADMIN
INSERT INTO USUARIO_ROL (ID_USUARIO, ID_ROL) VALUES (1, 1);

-- Ubicacion
INSERT INTO UBICACION (ID_UBICACION, NOMBRE, DETALLE)
VALUES (1, 'Parqueo Principal', 'Nivel 1');

INSERT INTO UBICACION (ID_UBICACION, NOMBRE, DETALLE)
VALUES (2, 'Parqueo Secundario', 'Nivel 2');

-- Bahia
-- Agregar bahías de ejemplo
INSERT INTO BAHIA (ID_BAHIA, CODIGO, DESCRIPCION, ID_UBICACION, ID_ESTADO, TIPO)
VALUES (1, 'B-01', 'Bahía 01', 1, 1, 'NORMAL');

INSERT INTO BAHIA (ID_BAHIA, CODIGO, DESCRIPCION, ID_UBICACION, ID_ESTADO, TIPO)
VALUES (2, 'B-02', 'Bahía 02', 1, 1, 'NORMAL');

-- Parámetros del sistema
INSERT INTO PARAMETRO (ID_PARAMETRO, CLAVE, VALOR, DESCRIPCION)
VALUES (1, 'RESERVA_DURACION_MAX_MIN', '240', 'Duración máxima de una reserva en minutos');

INSERT INTO PARAMETRO (ID_PARAMETRO, CLAVE, VALOR, DESCRIPCION)
VALUES (2, 'RESERVA_ANTICIPACION_MIN', '30', 'Tiempo mínimo de anticipación para reservar (minutos)');

