-- EstadoBahia
INSERT INTO BAHIAS.ESTADO_BAHIA (ID_ESTADO,  NOMBRE, DESCRIPCION) VALUES (1, 'Disponible', 'Lista para ser utilizada');
INSERT INTO BAHIAS.ESTADO_BAHIA (ID_ESTADO,  NOMBRE, DESCRIPCION) VALUES (2, 'Ocupada', 'Actualmente en uso');
INSERT INTO BAHIAS.ESTADO_BAHIA (ID_ESTADO,  NOMBRE, DESCRIPCION) VALUES (3, 'Mantenimiento', 'En reparación o revisión');
INSERT INTO BAHIAS.ESTADO_BAHIA (ID_ESTADO,  NOMBRE, DESCRIPCION) VALUES (4, 'Inactiva', 'No disponible para uso');

-- Rol
INSERT INTO BAHIAS.ROL (ID_ROL, NAME, DESCRIPTION, STATUS) VALUES (1, 'ADMIN',    'Acceso total al sistema', 'A');
INSERT INTO BAHIAS.ROL (ID_ROL, NAME, DESCRIPTION, STATUS) VALUES (2, 'OPERADOR', 'Gestiona bahías y reservas', 'A');
INSERT INTO BAHIAS.ROL (ID_ROL, NAME, DESCRIPTION, STATUS) VALUES (3, 'CONSULTA', 'Solo puede ver reportes y estados', 'A');

-- Rol_Permiso

-- Relacionar con rol ADMIN
INSERT INTO USUARIO_ROL (ID_USUARIO, ID_ROL) VALUES (1, 1);

-- Ubicacion
INSERT INTO BAHIAS.UBICACION (ID_UBICACION, NOMBRE, DETALLE)
VALUES (1, 'Parqueo Principal', 'Nivel 1');

INSERT INTO BAHIAS.UBICACION (ID_UBICACION, NOMBRE, DETALLE)
VALUES (2, 'Parqueo Secundario', 'Nivel 2');

-- Bahia
-- Agregar bahías de ejemplo --arreglar campos
INSERT INTO BAHIA (ID_BAHIA, CODIGO, DESCRIPCION, ID_UBICACION, ID_ESTADO, TIPO)
VALUES (1, 'B-01', 'Bahía 01', 1, 1, 'NORMAL');

INSERT INTO BAHIA (ID_BAHIA, CODIGO, DESCRIPCION, ID_UBICACION, ID_ESTADO, TIPO)
VALUES (2, 'B-02', 'Bahía 02', 1, 1, 'NORMAL');

-- Parámetros del sistema
INSERT INTO PARAMETRO (ID_PARAMETRO, CLAVE, VALOR, DESCRIPCION)
VALUES (1, 'RESERVA_DURACION_MAX_MIN', '240', 'Duración máxima de una reserva en minutos');

INSERT INTO PARAMETRO (ID_PARAMETRO, CLAVE, VALOR, DESCRIPCION)
VALUES (2, 'RESERVA_ANTICIPACION_MIN', '30', 'Tiempo mínimo de anticipación para reservar (minutos)');

