/* ===================== ROL ===================== */
CREATE TABLE ROL (
  ID_ROL       NUMBER,
  NOMBRE       VARCHAR2(50)  NOT NULL,
  DESCRIPCION  VARCHAR2(200)
);

ALTER TABLE ROL ADD CONSTRAINT PK_ROL PRIMARY KEY (ID_ROL);

/* ===================== PERMISO ===================== */
CREATE TABLE PERMISO (
  ID_PERMISO   NUMBER,
  CODIGO       VARCHAR2(80)  NOT NULL,
  DESCRIPCION  VARCHAR2(200)
);

ALTER TABLE PERMISO ADD CONSTRAINT PK_PERMISO PRIMARY KEY (ID_PERMISO);
ALTER TABLE PERMISO ADD CONSTRAINT UQ_PERMISO_CODIGO UNIQUE (CODIGO);

/* ===================== ROL_PERMISO ===================== */
CREATE TABLE ROL_PERMISO (
  ID_ROL      NUMBER NOT NULL,
  ID_PERMISO  NUMBER NOT NULL
);

ALTER TABLE ROL_PERMISO
  ADD CONSTRAINT PK_ROL_PERMISO PRIMARY KEY (ID_ROL, ID_PERMISO);
ALTER TABLE ROL_PERMISO
  ADD CONSTRAINT FK_RP_ROL FOREIGN KEY (ID_ROL) REFERENCES ROL(ID_ROL);
ALTER TABLE ROL_PERMISO
  ADD CONSTRAINT FK_RP_PERMISO FOREIGN KEY (ID_PERMISO) REFERENCES PERMISO(ID_PERMISO);

/* ===================== USUARIO ===================== */
CREATE TABLE USUARIO (
  ID_USUARIO   NUMBER,
  USERNAME     VARCHAR2(50)  NOT NULL,
  NOMBRE       VARCHAR2(100) NOT NULL,
  EMAIL        VARCHAR2(120),
  HASH_PASS    VARCHAR2(255) NOT NULL,
  ACTIVO       CHAR(1) DEFAULT 'S' NOT NULL,
  CREADO_EN    TIMESTAMP DEFAULT SYSTIMESTAMP
);

ALTER TABLE USUARIO ADD CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO);
ALTER TABLE USUARIO ADD CONSTRAINT UQ_USUARIO_USERNAME UNIQUE (USERNAME);
ALTER TABLE USUARIO ADD CONSTRAINT UQ_USUARIO_EMAIL UNIQUE (EMAIL);
ALTER TABLE USUARIO ADD CONSTRAINT CK_USUARIO_ACTIVO CHECK (ACTIVO IN ('S','N'));

/* ===================== USUARIO_ROL ===================== */
CREATE TABLE USUARIO_ROL (
  ID_USUARIO  NUMBER NOT NULL,
  ID_ROL      NUMBER NOT NULL
);

ALTER TABLE USUARIO_ROL
  ADD CONSTRAINT PK_USUARIO_ROL PRIMARY KEY (ID_USUARIO, ID_ROL);
ALTER TABLE USUARIO_ROL
  ADD CONSTRAINT FK_UR_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO);
ALTER TABLE USUARIO_ROL
  ADD CONSTRAINT FK_UR_ROL FOREIGN KEY (ID_ROL) REFERENCES ROL(ID_ROL);

/* ===================== UBICACION ===================== */
CREATE TABLE UBICACION (
  ID_UBICACION  NUMBER,
  NOMBRE        VARCHAR2(80) NOT NULL,
  DETALLE       VARCHAR2(200)
);

ALTER TABLE UBICACION ADD CONSTRAINT PK_UBICACION PRIMARY KEY (ID_UBICACION);

/* ===================== ESTADO_BAHIA ===================== */
CREATE TABLE ESTADO_BAHIA (
  ID_ESTADO     NUMBER,
  CODIGO        VARCHAR2(30) NOT NULL,
  NOMBRE        VARCHAR2(60) NOT NULL
);

ALTER TABLE ESTADO_BAHIA ADD CONSTRAINT PK_ESTADO_BAHIA PRIMARY KEY (ID_ESTADO);
ALTER TABLE ESTADO_BAHIA ADD CONSTRAINT UQ_ESTADO_CODIGO UNIQUE (CODIGO);

/* ===================== BAHIA ===================== */
CREATE TABLE BAHIA (
  ID_BAHIA       NUMBER,
  CODIGO         VARCHAR2(30) NOT NULL,
  DESCRIPCION    VARCHAR2(150),
  ID_UBICACION   NUMBER,
  ID_ESTADO      NUMBER NOT NULL,
  TIPO           VARCHAR2(30),
  ACTIVA         CHAR(1) DEFAULT 'S' NOT NULL,
  FECHA_CREACION TIMESTAMP DEFAULT SYSTIMESTAMP
);

ALTER TABLE BAHIA ADD CONSTRAINT PK_BAHIA PRIMARY KEY (ID_BAHIA);
ALTER TABLE BAHIA ADD CONSTRAINT UQ_BAHIA_CODIGO UNIQUE (CODIGO);
ALTER TABLE BAHIA ADD CONSTRAINT CK_BAHIA_ACTIVA CHECK (ACTIVA IN ('S','N'));
ALTER TABLE BAHIA
  ADD CONSTRAINT FK_BAHIA_UBICACION FOREIGN KEY (ID_UBICACION) REFERENCES UBICACION(ID_UBICACION);
ALTER TABLE BAHIA
  ADD CONSTRAINT FK_BAHIA_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO_BAHIA(ID_ESTADO);

CREATE INDEX IX_BAHIA_UBIC   ON BAHIA(ID_UBICACION);
CREATE INDEX IX_BAHIA_ESTADO ON BAHIA(ID_ESTADO);

/* ===================== RESERVA ===================== */
CREATE TABLE RESERVA (
  ID_RESERVA   NUMBER,
  ID_BAHIA     NUMBER NOT NULL,
  ID_USUARIO   NUMBER NOT NULL,
  INICIO_TS    TIMESTAMP NOT NULL,
  FIN_TS       TIMESTAMP NOT NULL,
  ESTADO       VARCHAR2(20) DEFAULT 'RESERVADA' NOT NULL,
  OBSERVACION  VARCHAR2(300),
  CREADO_EN    TIMESTAMP DEFAULT SYSTIMESTAMP
);

ALTER TABLE RESERVA ADD CONSTRAINT PK_RESERVA PRIMARY KEY (ID_RESERVA);
ALTER TABLE RESERVA ADD CONSTRAINT CK_RES_FECHAS CHECK (FIN_TS > INICIO_TS);
ALTER TABLE RESERVA ADD CONSTRAINT CK_RES_ESTADO CHECK (ESTADO IN ('RESERVADA','CANCELADA','FINALIZADA'));
ALTER TABLE RESERVA
  ADD CONSTRAINT FK_RES_BAHIA FOREIGN KEY (ID_BAHIA) REFERENCES BAHIA(ID_BAHIA);
ALTER TABLE RESERVA
  ADD CONSTRAINT FK_RES_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO);

CREATE INDEX IX_RES_BAHIA_TIME ON RESERVA(ID_BAHIA, INICIO_TS, FIN_TS);

/* ===================== HISTORIAL_BAHIA ===================== */
CREATE TABLE HISTORIAL_BAHIA (
  ID_HISTORIAL   NUMBER,
  ID_BAHIA       NUMBER NOT NULL,
  ESTADO_ANT     VARCHAR2(30),
  ESTADO_NUEVO   VARCHAR2(30),
  FECHA_CAMBIO   TIMESTAMP DEFAULT SYSTIMESTAMP,
  USUARIO_ACCION VARCHAR2(100)
);

ALTER TABLE HISTORIAL_BAHIA ADD CONSTRAINT PK_HISTORIAL_BAHIA PRIMARY KEY (ID_HISTORIAL);
ALTER TABLE HISTORIAL_BAHIA
  ADD CONSTRAINT FK_HIST_BAHIA FOREIGN KEY (ID_BAHIA) REFERENCES BAHIA(ID_BAHIA);

/* ===================== PARAMETRO ===================== */
CREATE TABLE PARAMETRO (
  ID_PARAMETRO NUMBER,
  CLAVE        VARCHAR2(80) NOT NULL,
  VALOR        VARCHAR2(4000) NOT NULL,
  DESCRIPCION  VARCHAR2(200)
);

ALTER TABLE PARAMETRO ADD CONSTRAINT PK_PARAMETRO PRIMARY KEY (ID_PARAMETRO);
ALTER TABLE PARAMETRO ADD CONSTRAINT UQ_PARAMETRO_CLAVE UNIQUE (CLAVE);

/* ===================== REPORTE_EJECUCION ===================== */
CREATE TABLE REPORTE_EJECUCION (
  ID_REPORTE    NUMBER,
  CODIGO        VARCHAR2(80) NOT NULL,
  PARAMS_JSON   CLOB,
  GENERADO_POR  NUMBER,
  GENERADO_EN   TIMESTAMP DEFAULT SYSTIMESTAMP,
  OUTPUT_URL    VARCHAR2(400)
);

ALTER TABLE REPORTE_EJECUCION ADD CONSTRAINT PK_REPORTE PRIMARY KEY (ID_REPORTE);
ALTER TABLE REPORTE_EJECUCION
  ADD CONSTRAINT FK_REP_USER FOREIGN KEY (GENERADO_POR) REFERENCES USUARIO(ID_USUARIO);

/* ===================== VEHICULO ===================== */
CREATE TABLE VEHICULO (
  ID_VEHICULO  NUMBER,
  PLACA        VARCHAR2(15)  NOT NULL,     -- matrícula
  MARCA        VARCHAR2(50),
  MODELO       VARCHAR2(50),
  COLOR        VARCHAR2(30),
  TIPO         NUMBER NOT NULL,               -- AUTO, MOTO, CAMIONETA, etc.
  ID_USUARIO   NUMBER,                     -- dueño/registrante (opcional)
  ACTIVO       CHAR(1) DEFAULT 'S' NOT NULL,
  CREADO_EN    TIMESTAMP DEFAULT SYSTIMESTAMP
);

ALTER TABLE VEHICULO ADD CONSTRAINT PK_VEHICULO PRIMARY KEY (ID_VEHICULO);
ALTER TABLE VEHICULO ADD CONSTRAINT UQ_VEHICULO_PLACA UNIQUE (PLACA);
ALTER TABLE VEHICULO ADD CONSTRAINT CK_VEHICULO_ACTIVO CHECK (ACTIVO IN ('S','N'));
ALTER TABLE VEHICULO
  ADD CONSTRAINT FK_VEHICULO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO);
ALTER TABLE VEHICULO
  ADD CONSTRAINT FK_VEHICULO_TIPO FOREIGN KEY (TIPO) REFERENCES TIPO_VEHICULO(ID_TIPO);

CREATE INDEX IX_VEHICULO_USUARIO ON VEHICULO(ID_USUARIO);

/* ===================== TIPO VEHICULO ===================== */
CREATE TABLE TIPO_VEHICULO (
  ID_TIPO      NUMBER,
  NOMBRE       VARCHAR2(50) NOT NULL,
  DESCRIPCION  VARCHAR2(200),
  ICON     VARCHAR2(100)
);

ALTER TABLE TIPO_VEHICULO ADD CONSTRAINT PK_TIPO_VEHICULO PRIMARY KEY (ID_TIPO);
ALTER TABLE TIPO_VEHICULO ADD CONSTRAINT UQ_TIPO_NOMBRE UNIQUE (NOMBRE);
