-- Usuario esquema principal
CREATE USER BAHIAS_SCHM IDENTIFIED BY "Luis1234";
-- Usuario de operaciones
CREATE USER OP_BAHIAS IDENTIFIED BY "Luis1234";
-- Usuario de solo consulta
CREATE USER USR_CONSULTA_BAHIAS IDENTIFIED BY "Luis1234";
-- Usuario personal
CREATE USER LALMAZAN IDENTIFIED BY "Luis1234";

-- Permisos esquema principal
GRANT CONNECT, RESOURCE TO BAHIAS_SCHM;
GRANT UNLIMITED TABLESPACE TO BAHIAS_SCHM;
GRANT CREATE VIEW TO BAHIAS_SCHM;
GRANT CREATE PROCEDURE TO BAHIAS_SCHM;
GRANT CREATE SEQUENCE TO BAHIAS_SCHM;
GRANT CREATE TRIGGER TO BAHIAS_SCHM;
GRANT CREATE SYNONYM TO BAHIAS_SCHM;
GRANT CREATE TYPE TO BAHIAS_SCHM;


-- Permisos usuario de operaciones
GRANT CONNECT TO OP_BAHIAS;
GRANT UNLIMITED TABLESPACE TO OP_BAHIAS;
GRANT CREATE SESSION TO OP_BAHIAS;
GRANT SELECT, INSERT, UPDATE, DELETE ON BAHIAS_SCHM.* TO OP_BAHIAS;

-- Permisos usuario de solo consulta
GRANT CONNECT TO USR_CONSULTA_BAHIAS;
GRANT UNLIMITED TABLESPACE TO USR_CONSULTA_BAHIAS;
GRANT CREATE SESSION TO USR_CONSULTA_BAHIAS;
GRANT SELECT ANY TABLE TO USR_CONSULTA_BAHIAS;

