ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

CREATE USER BAHIAS IDENTIFIED BY BAHIAS123;
GRANT CREATE SESSION, RESOURCE, TO BAHIAS;
GRANT CREATE JOB TO BAHIAS;

CREATE USER OP_BAHIAS IDENTIFIED BY OP_BAHIAS123;
GRANT CREATE SESSION TO OP_BAHIAS;
GRANT CONNECT TO OP_BAHIAS;

CREATE USER USR_CONSULTA_BAHIAS IDENTIFIED BY USR_CONSULTA_BAHIAS123;
GRANT CREATE SESSION TO USR_CONSULTA_BAHIAS;
GRANT CONNECT TO USR_CONSULTA_BAHIAS;
---Usuario para desarrollo
CREATE USER LALMAZAN IDENTIFIED BY "Luis1234";
GRANT CREATE SESSION TO LALMAZAN;
GRANT CONNECT TO LALMAZAN;
GRANT DBA TO LALMAZAN;

CREATE USER CRODRIGUEZ IDENTIFIED BY "Manager1";
GRANT CREATE SESSION TO CRODRIGUEZ;
GRANT CONNECT TO CRODRIGUEZ;
GRANT DBA TO CRODRIGUEZ;


CREATE USER JBARILLAS IDENTIFIED BY "Manager1";
GRANT CREATE SESSION TO JBARILLAS;
GRANT CONNECT TO JBARILLAS;
GRANT DBA TO JBARILLAS;


ALTER USER BAHIAS QUOTA UNLIMITED ON USERS;
ALTER USER OP_BAHIAS QUOTA UNLIMITED ON USERS;
ALTER USER USR_CONSULTA_BAHIAS QUOTA UNLIMITED ON USERS;

--ROLES
CREATE ROLE SELECT_BAHIAS; 

-- Permisos para el rol SELECT_BAHIAS
GRANT SELECT_BAHIAS TO USR_CONSULTA_BAHIAS;

-- Trigger para otorgar permisos automáticamente al crear tablas
CREATE OR REPLACE TRIGGER BAHIAS.TRG_GRANT_SELECT
AFTER CREATE ON SCHEMA
DECLARE
  job_name  VARCHAR2(128);
BEGIN
  IF ora_dict_obj_type = 'TABLE' THEN
    job_name := 'J_GRANT_'||ora_dict_obj_name||'_'||TO_CHAR(SYSTIMESTAMP,'YYYYMMDDHH24MISSFF3');

    DBMS_SCHEDULER.create_job(
      job_name   => job_name,
      job_type   => 'PLSQL_BLOCK',
      job_action => 'BEGIN '||
                    '  EXECUTE IMMEDIATE ''GRANT SELECT ON BAHIAS.'||ora_dict_obj_name||' TO SELECT_BAHIAS'';'||
                    'END;',
      start_date => SYSTIMESTAMP + INTERVAL '5' SECOND,  -- corre fuera del DDL
      enabled    => TRUE,
      auto_drop  => TRUE
    );
  END IF;
END;


SELECT owner, table_name, privilege
FROM   dba_tab_privs
WHERE  grantee = 'SELECT_BAHIAS'



CREATE ROLE OPERACIONES_BAHIAS; 

-- Permisos para el rol SELECT_BAHIAS
GRANT OPERACIONES_BAHIAS TO OP_BAHIAS;

-- Trigger para otorgar permisos automáticamente al crear tablas
CREATE OR REPLACE TRIGGER BAHIAS.TRG_GRANT_OPERACIONES
AFTER CREATE ON SCHEMA
DECLARE
  job_name  VARCHAR2(128);
BEGIN
  IF ora_dict_obj_type = 'TABLE' THEN
    job_name := 'J_GRANT_'||ora_dict_obj_name||'_'||TO_CHAR(SYSTIMESTAMP,'YYYYMMDDHH24MISSFF3');

    DBMS_SCHEDULER.create_job(
      job_name   => job_name,
      job_type   => 'PLSQL_BLOCK',
      job_action => 'BEGIN '||
                    '  EXECUTE IMMEDIATE ''GRANT SELECT, INSERT, UPDATE, DELETE ON BAHIAS.'||ora_dict_obj_name||' TO OPERACIONES_BAHIAS'';'||
                    'END;',
      start_date => SYSTIMESTAMP + INTERVAL '5' SECOND,  -- corre fuera del DDL
      enabled    => TRUE,
      auto_drop  => TRUE
    );
  END IF;
END;
